on:
    push:
      branches:
        - main

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    # - name: 📂 Copy .envproduction to .env
    #   run: |
    #     cp .envproduction .env

    # - name: 📂 Copy p.htaccess to .htaccess
    #   run: |
    #     cp p.htaccess .htaccess


    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
          server:   ${{ secrets.LARAVEL_SERVER }}
          port:     ${{ secrets.LARAVEL_PORT }}
          username: ${{ secrets.LARAVEL_USER }}
          password: ${{ secrets.LARAVEL_PASS }}

